### ISSUE TITLE
Release on F-Droid?

### ISSUE THREAD

**Issue by TPS** [zom/zom-android#1]
@iamironrabbit, @n8fr8: Apparently, this has never been released to _any_ F-Droid repo I can locate.  Are there plans to do so for the main, Guardian Projects', @IzzySoft's, &c?

**Comment by IzzySoft** [comment]
@TPS I doubt it. Reasons:

* last commit 9/2022
* APK size closing up to the limit of my repo (it's already 29 MB now, growing about 0.5 MB with each release)
* no license at all
* no description, no screenshots …

**Comment by iamironrabbit** [comment]
Thank you for the interest, but no. We are discontinuing this client in favor of recommending the very excellent https://fluffychat.im/

We will still operate our own zom.im matrix service, and offer our own hosted web interfaces.
